version: "2"

run:
  timeout: 5m

linters:
  default: all
  disable:
    - wsl
    - wsl_v5
  
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - cyclop
          - gocyclo
      - path: 'mocks/(.+)\.go'
        linters:
          - dupl

formatters:
  enable:
    - gofmt
    - goimports
  
  settings:
    goimports:
      local-prefixes:
        - github.com/jchevertonwynne/ssanta

    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      case-max-lines: 0
      cuddle-max-statements: 1
      default: ~ # Can be `all`, `none`, `default` or empty
      enable:
        - append
        - assign
        - branch
        - decl
        - defer
        - err
        - expr
        - for
        - go
        - if
        - inc-dec
        - label
        - range
        - return
        - select
        - send
        - switch
        - type-switch
        - leading-whitespace
        - trailing-whitespace
      disable:
        - after-block
        - after-decl
        - after-defer
        - after-expr
        - after-go
        - assign-exclusive
        - assign-expr
