version: "2"

run:
  timeout: 5m

linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - ireturn
    - lll
    - mnd
    - nlreturn
    - noinlineerr
    - revive
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - cyclop
          - gocyclo
      - path: 'mocks/(.+)\.go'
        linters:
          - dupl

formatters:
  enable:
    - gofmt
    - goimports
  
  settings:
    goimports:
      local-prefixes:
        - github.com/jchevertonwynne/ssanta

