// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -typed -source=interfaces.go -destination=mocks/mock_interfaces.go -package=storemocks
//

// Package storemocks is a generated GoMock package.
package storemocks

import (
	context "context"
	reflect "reflect"
	time "time"

	store "github.com/jchevertonwynne/ssanta/internal/store"
	gomock "go.uber.org/mock/gomock"
)

// MockUserStore is a mock of UserStore interface.
type MockUserStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserStoreMockRecorder
	isgomock struct{}
}

// MockUserStoreMockRecorder is the mock recorder for MockUserStore.
type MockUserStoreMockRecorder struct {
	mock *MockUserStore
}

// NewMockUserStore creates a new mock instance.
func NewMockUserStore(ctrl *gomock.Controller) *MockUserStore {
	mock := &MockUserStore{ctrl: ctrl}
	mock.recorder = &MockUserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStore) EXPECT() *MockUserStoreMockRecorder {
	return m.recorder
}

// BumpSessionVersion mocks base method.
func (m *MockUserStore) BumpSessionVersion(ctx context.Context, id store.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BumpSessionVersion", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// BumpSessionVersion indicates an expected call of BumpSessionVersion.
func (mr *MockUserStoreMockRecorder) BumpSessionVersion(ctx, id any) *MockUserStoreBumpSessionVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BumpSessionVersion", reflect.TypeOf((*MockUserStore)(nil).BumpSessionVersion), ctx, id)
	return &MockUserStoreBumpSessionVersionCall{Call: call}
}

// MockUserStoreBumpSessionVersionCall wrap *gomock.Call
type MockUserStoreBumpSessionVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserStoreBumpSessionVersionCall) Return(arg0 error) *MockUserStoreBumpSessionVersionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserStoreBumpSessionVersionCall) Do(f func(context.Context, store.UserID) error) *MockUserStoreBumpSessionVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserStoreBumpSessionVersionCall) DoAndReturn(f func(context.Context, store.UserID) error) *MockUserStoreBumpSessionVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateUser mocks base method.
func (m *MockUserStore) CreateUser(ctx context.Context, username, passwordHash string) (store.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, username, passwordHash)
	ret0, _ := ret[0].(store.UserID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserStoreMockRecorder) CreateUser(ctx, username, passwordHash any) *MockUserStoreCreateUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserStore)(nil).CreateUser), ctx, username, passwordHash)
	return &MockUserStoreCreateUserCall{Call: call}
}

// MockUserStoreCreateUserCall wrap *gomock.Call
type MockUserStoreCreateUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserStoreCreateUserCall) Return(arg0 store.UserID, arg1 error) *MockUserStoreCreateUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserStoreCreateUserCall) Do(f func(context.Context, string, string) (store.UserID, error)) *MockUserStoreCreateUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserStoreCreateUserCall) DoAndReturn(f func(context.Context, string, string) (store.UserID, error)) *MockUserStoreCreateUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteUser mocks base method.
func (m *MockUserStore) DeleteUser(ctx context.Context, id store.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserStoreMockRecorder) DeleteUser(ctx, id any) *MockUserStoreDeleteUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserStore)(nil).DeleteUser), ctx, id)
	return &MockUserStoreDeleteUserCall{Call: call}
}

// MockUserStoreDeleteUserCall wrap *gomock.Call
type MockUserStoreDeleteUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserStoreDeleteUserCall) Return(arg0 error) *MockUserStoreDeleteUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserStoreDeleteUserCall) Do(f func(context.Context, store.UserID) error) *MockUserStoreDeleteUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserStoreDeleteUserCall) DoAndReturn(f func(context.Context, store.UserID) error) *MockUserStoreDeleteUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUserByID mocks base method.
func (m *MockUserStore) GetUserByID(ctx context.Context, id store.UserID) (store.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(store.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserStoreMockRecorder) GetUserByID(ctx, id any) *MockUserStoreGetUserByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserStore)(nil).GetUserByID), ctx, id)
	return &MockUserStoreGetUserByIDCall{Call: call}
}

// MockUserStoreGetUserByIDCall wrap *gomock.Call
type MockUserStoreGetUserByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserStoreGetUserByIDCall) Return(arg0 store.User, arg1 error) *MockUserStoreGetUserByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserStoreGetUserByIDCall) Do(f func(context.Context, store.UserID) (store.User, error)) *MockUserStoreGetUserByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserStoreGetUserByIDCall) DoAndReturn(f func(context.Context, store.UserID) (store.User, error)) *MockUserStoreGetUserByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUserByUsername mocks base method.
func (m *MockUserStore) GetUserByUsername(ctx context.Context, username string) (store.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(store.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockUserStoreMockRecorder) GetUserByUsername(ctx, username any) *MockUserStoreGetUserByUsernameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockUserStore)(nil).GetUserByUsername), ctx, username)
	return &MockUserStoreGetUserByUsernameCall{Call: call}
}

// MockUserStoreGetUserByUsernameCall wrap *gomock.Call
type MockUserStoreGetUserByUsernameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserStoreGetUserByUsernameCall) Return(arg0 store.User, arg1 error) *MockUserStoreGetUserByUsernameCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserStoreGetUserByUsernameCall) Do(f func(context.Context, string) (store.User, error)) *MockUserStoreGetUserByUsernameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserStoreGetUserByUsernameCall) DoAndReturn(f func(context.Context, string) (store.User, error)) *MockUserStoreGetUserByUsernameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUserSessionVersion mocks base method.
func (m *MockUserStore) GetUserSessionVersion(ctx context.Context, id store.UserID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSessionVersion", ctx, id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSessionVersion indicates an expected call of GetUserSessionVersion.
func (mr *MockUserStoreMockRecorder) GetUserSessionVersion(ctx, id any) *MockUserStoreGetUserSessionVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSessionVersion", reflect.TypeOf((*MockUserStore)(nil).GetUserSessionVersion), ctx, id)
	return &MockUserStoreGetUserSessionVersionCall{Call: call}
}

// MockUserStoreGetUserSessionVersionCall wrap *gomock.Call
type MockUserStoreGetUserSessionVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserStoreGetUserSessionVersionCall) Return(arg0 int, arg1 error) *MockUserStoreGetUserSessionVersionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserStoreGetUserSessionVersionCall) Do(f func(context.Context, store.UserID) (int, error)) *MockUserStoreGetUserSessionVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserStoreGetUserSessionVersionCall) DoAndReturn(f func(context.Context, store.UserID) (int, error)) *MockUserStoreGetUserSessionVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUserWithPassword mocks base method.
func (m *MockUserStore) GetUserWithPassword(ctx context.Context, username string) (store.UserWithPassword, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWithPassword", ctx, username)
	ret0, _ := ret[0].(store.UserWithPassword)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWithPassword indicates an expected call of GetUserWithPassword.
func (mr *MockUserStoreMockRecorder) GetUserWithPassword(ctx, username any) *MockUserStoreGetUserWithPasswordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWithPassword", reflect.TypeOf((*MockUserStore)(nil).GetUserWithPassword), ctx, username)
	return &MockUserStoreGetUserWithPasswordCall{Call: call}
}

// MockUserStoreGetUserWithPasswordCall wrap *gomock.Call
type MockUserStoreGetUserWithPasswordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserStoreGetUserWithPasswordCall) Return(arg0 store.UserWithPassword, arg1 error) *MockUserStoreGetUserWithPasswordCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserStoreGetUserWithPasswordCall) Do(f func(context.Context, string) (store.UserWithPassword, error)) *MockUserStoreGetUserWithPasswordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserStoreGetUserWithPasswordCall) DoAndReturn(f func(context.Context, string) (store.UserWithPassword, error)) *MockUserStoreGetUserWithPasswordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUserWithPasswordByID mocks base method.
func (m *MockUserStore) GetUserWithPasswordByID(ctx context.Context, id store.UserID) (store.UserWithPassword, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWithPasswordByID", ctx, id)
	ret0, _ := ret[0].(store.UserWithPassword)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWithPasswordByID indicates an expected call of GetUserWithPasswordByID.
func (mr *MockUserStoreMockRecorder) GetUserWithPasswordByID(ctx, id any) *MockUserStoreGetUserWithPasswordByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWithPasswordByID", reflect.TypeOf((*MockUserStore)(nil).GetUserWithPasswordByID), ctx, id)
	return &MockUserStoreGetUserWithPasswordByIDCall{Call: call}
}

// MockUserStoreGetUserWithPasswordByIDCall wrap *gomock.Call
type MockUserStoreGetUserWithPasswordByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserStoreGetUserWithPasswordByIDCall) Return(arg0 store.UserWithPassword, arg1 error) *MockUserStoreGetUserWithPasswordByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserStoreGetUserWithPasswordByIDCall) Do(f func(context.Context, store.UserID) (store.UserWithPassword, error)) *MockUserStoreGetUserWithPasswordByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserStoreGetUserWithPasswordByIDCall) DoAndReturn(f func(context.Context, store.UserID) (store.UserWithPassword, error)) *MockUserStoreGetUserWithPasswordByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GrantAdmin mocks base method.
func (m *MockUserStore) GrantAdmin(ctx context.Context, targetID, grantedBy store.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantAdmin", ctx, targetID, grantedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// GrantAdmin indicates an expected call of GrantAdmin.
func (mr *MockUserStoreMockRecorder) GrantAdmin(ctx, targetID, grantedBy any) *MockUserStoreGrantAdminCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantAdmin", reflect.TypeOf((*MockUserStore)(nil).GrantAdmin), ctx, targetID, grantedBy)
	return &MockUserStoreGrantAdminCall{Call: call}
}

// MockUserStoreGrantAdminCall wrap *gomock.Call
type MockUserStoreGrantAdminCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserStoreGrantAdminCall) Return(arg0 error) *MockUserStoreGrantAdminCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserStoreGrantAdminCall) Do(f func(context.Context, store.UserID, store.UserID) error) *MockUserStoreGrantAdminCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserStoreGrantAdminCall) DoAndReturn(f func(context.Context, store.UserID, store.UserID) error) *MockUserStoreGrantAdminCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsUserAdmin mocks base method.
func (m *MockUserStore) IsUserAdmin(ctx context.Context, id store.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserAdmin", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserAdmin indicates an expected call of IsUserAdmin.
func (mr *MockUserStoreMockRecorder) IsUserAdmin(ctx, id any) *MockUserStoreIsUserAdminCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserAdmin", reflect.TypeOf((*MockUserStore)(nil).IsUserAdmin), ctx, id)
	return &MockUserStoreIsUserAdminCall{Call: call}
}

// MockUserStoreIsUserAdminCall wrap *gomock.Call
type MockUserStoreIsUserAdminCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserStoreIsUserAdminCall) Return(arg0 bool, arg1 error) *MockUserStoreIsUserAdminCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserStoreIsUserAdminCall) Do(f func(context.Context, store.UserID) (bool, error)) *MockUserStoreIsUserAdminCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserStoreIsUserAdminCall) DoAndReturn(f func(context.Context, store.UserID) (bool, error)) *MockUserStoreIsUserAdminCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListAllUsers mocks base method.
func (m *MockUserStore) ListAllUsers(ctx context.Context) ([]store.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllUsers", ctx)
	ret0, _ := ret[0].([]store.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllUsers indicates an expected call of ListAllUsers.
func (mr *MockUserStoreMockRecorder) ListAllUsers(ctx any) *MockUserStoreListAllUsersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllUsers", reflect.TypeOf((*MockUserStore)(nil).ListAllUsers), ctx)
	return &MockUserStoreListAllUsersCall{Call: call}
}

// MockUserStoreListAllUsersCall wrap *gomock.Call
type MockUserStoreListAllUsersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserStoreListAllUsersCall) Return(arg0 []store.AdminUser, arg1 error) *MockUserStoreListAllUsersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserStoreListAllUsersCall) Do(f func(context.Context) ([]store.AdminUser, error)) *MockUserStoreListAllUsersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserStoreListAllUsersCall) DoAndReturn(f func(context.Context) ([]store.AdminUser, error)) *MockUserStoreListAllUsersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListUsers mocks base method.
func (m *MockUserStore) ListUsers(ctx context.Context) ([]store.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx)
	ret0, _ := ret[0].([]store.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUserStoreMockRecorder) ListUsers(ctx any) *MockUserStoreListUsersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUserStore)(nil).ListUsers), ctx)
	return &MockUserStoreListUsersCall{Call: call}
}

// MockUserStoreListUsersCall wrap *gomock.Call
type MockUserStoreListUsersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserStoreListUsersCall) Return(arg0 []store.User, arg1 error) *MockUserStoreListUsersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserStoreListUsersCall) Do(f func(context.Context) ([]store.User, error)) *MockUserStoreListUsersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserStoreListUsersCall) DoAndReturn(f func(context.Context) ([]store.User, error)) *MockUserStoreListUsersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RevokeAdmin mocks base method.
func (m *MockUserStore) RevokeAdmin(ctx context.Context, targetID store.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAdmin", ctx, targetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAdmin indicates an expected call of RevokeAdmin.
func (mr *MockUserStoreMockRecorder) RevokeAdmin(ctx, targetID any) *MockUserStoreRevokeAdminCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAdmin", reflect.TypeOf((*MockUserStore)(nil).RevokeAdmin), ctx, targetID)
	return &MockUserStoreRevokeAdminCall{Call: call}
}

// MockUserStoreRevokeAdminCall wrap *gomock.Call
type MockUserStoreRevokeAdminCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserStoreRevokeAdminCall) Return(arg0 error) *MockUserStoreRevokeAdminCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserStoreRevokeAdminCall) Do(f func(context.Context, store.UserID) error) *MockUserStoreRevokeAdminCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserStoreRevokeAdminCall) DoAndReturn(f func(context.Context, store.UserID) error) *MockUserStoreRevokeAdminCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdatePasswordHash mocks base method.
func (m *MockUserStore) UpdatePasswordHash(ctx context.Context, id store.UserID, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasswordHash", ctx, id, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePasswordHash indicates an expected call of UpdatePasswordHash.
func (mr *MockUserStoreMockRecorder) UpdatePasswordHash(ctx, id, passwordHash any) *MockUserStoreUpdatePasswordHashCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordHash", reflect.TypeOf((*MockUserStore)(nil).UpdatePasswordHash), ctx, id, passwordHash)
	return &MockUserStoreUpdatePasswordHashCall{Call: call}
}

// MockUserStoreUpdatePasswordHashCall wrap *gomock.Call
type MockUserStoreUpdatePasswordHashCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserStoreUpdatePasswordHashCall) Return(arg0 error) *MockUserStoreUpdatePasswordHashCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserStoreUpdatePasswordHashCall) Do(f func(context.Context, store.UserID, string) error) *MockUserStoreUpdatePasswordHashCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserStoreUpdatePasswordHashCall) DoAndReturn(f func(context.Context, store.UserID, string) error) *MockUserStoreUpdatePasswordHashCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UserExists mocks base method.
func (m *MockUserStore) UserExists(ctx context.Context, id store.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserExists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserExists indicates an expected call of UserExists.
func (mr *MockUserStoreMockRecorder) UserExists(ctx, id any) *MockUserStoreUserExistsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserExists", reflect.TypeOf((*MockUserStore)(nil).UserExists), ctx, id)
	return &MockUserStoreUserExistsCall{Call: call}
}

// MockUserStoreUserExistsCall wrap *gomock.Call
type MockUserStoreUserExistsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserStoreUserExistsCall) Return(arg0 bool, arg1 error) *MockUserStoreUserExistsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserStoreUserExistsCall) Do(f func(context.Context, store.UserID) (bool, error)) *MockUserStoreUserExistsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserStoreUserExistsCall) DoAndReturn(f func(context.Context, store.UserID) (bool, error)) *MockUserStoreUserExistsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRoomStore is a mock of RoomStore interface.
type MockRoomStore struct {
	ctrl     *gomock.Controller
	recorder *MockRoomStoreMockRecorder
	isgomock struct{}
}

// MockRoomStoreMockRecorder is the mock recorder for MockRoomStore.
type MockRoomStoreMockRecorder struct {
	mock *MockRoomStore
}

// NewMockRoomStore creates a new mock instance.
func NewMockRoomStore(ctrl *gomock.Controller) *MockRoomStore {
	mock := &MockRoomStore{ctrl: ctrl}
	mock.recorder = &MockRoomStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomStore) EXPECT() *MockRoomStoreMockRecorder {
	return m.recorder
}

// AdminDeleteRoom mocks base method.
func (m *MockRoomStore) AdminDeleteRoom(ctx context.Context, roomID store.RoomID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminDeleteRoom", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminDeleteRoom indicates an expected call of AdminDeleteRoom.
func (mr *MockRoomStoreMockRecorder) AdminDeleteRoom(ctx, roomID any) *MockRoomStoreAdminDeleteRoomCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminDeleteRoom", reflect.TypeOf((*MockRoomStore)(nil).AdminDeleteRoom), ctx, roomID)
	return &MockRoomStoreAdminDeleteRoomCall{Call: call}
}

// MockRoomStoreAdminDeleteRoomCall wrap *gomock.Call
type MockRoomStoreAdminDeleteRoomCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreAdminDeleteRoomCall) Return(arg0 error) *MockRoomStoreAdminDeleteRoomCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreAdminDeleteRoomCall) Do(f func(context.Context, store.RoomID) error) *MockRoomStoreAdminDeleteRoomCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreAdminDeleteRoomCall) DoAndReturn(f func(context.Context, store.RoomID) error) *MockRoomStoreAdminDeleteRoomCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ClearExpiredRoomPGPChallenges mocks base method.
func (m *MockRoomStore) ClearExpiredRoomPGPChallenges(ctx context.Context, now time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearExpiredRoomPGPChallenges", ctx, now)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearExpiredRoomPGPChallenges indicates an expected call of ClearExpiredRoomPGPChallenges.
func (mr *MockRoomStoreMockRecorder) ClearExpiredRoomPGPChallenges(ctx, now any) *MockRoomStoreClearExpiredRoomPGPChallengesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearExpiredRoomPGPChallenges", reflect.TypeOf((*MockRoomStore)(nil).ClearExpiredRoomPGPChallenges), ctx, now)
	return &MockRoomStoreClearExpiredRoomPGPChallengesCall{Call: call}
}

// MockRoomStoreClearExpiredRoomPGPChallengesCall wrap *gomock.Call
type MockRoomStoreClearExpiredRoomPGPChallengesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreClearExpiredRoomPGPChallengesCall) Return(arg0 int64, arg1 error) *MockRoomStoreClearExpiredRoomPGPChallengesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreClearExpiredRoomPGPChallengesCall) Do(f func(context.Context, time.Time) (int64, error)) *MockRoomStoreClearExpiredRoomPGPChallengesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreClearExpiredRoomPGPChallengesCall) DoAndReturn(f func(context.Context, time.Time) (int64, error)) *MockRoomStoreClearExpiredRoomPGPChallengesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ClearRoomUserPGPKey mocks base method.
func (m *MockRoomStore) ClearRoomUserPGPKey(ctx context.Context, roomID store.RoomID, userID store.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearRoomUserPGPKey", ctx, roomID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearRoomUserPGPKey indicates an expected call of ClearRoomUserPGPKey.
func (mr *MockRoomStoreMockRecorder) ClearRoomUserPGPKey(ctx, roomID, userID any) *MockRoomStoreClearRoomUserPGPKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearRoomUserPGPKey", reflect.TypeOf((*MockRoomStore)(nil).ClearRoomUserPGPKey), ctx, roomID, userID)
	return &MockRoomStoreClearRoomUserPGPKeyCall{Call: call}
}

// MockRoomStoreClearRoomUserPGPKeyCall wrap *gomock.Call
type MockRoomStoreClearRoomUserPGPKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreClearRoomUserPGPKeyCall) Return(arg0 error) *MockRoomStoreClearRoomUserPGPKeyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreClearRoomUserPGPKeyCall) Do(f func(context.Context, store.RoomID, store.UserID) error) *MockRoomStoreClearRoomUserPGPKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreClearRoomUserPGPKeyCall) DoAndReturn(f func(context.Context, store.RoomID, store.UserID) error) *MockRoomStoreClearRoomUserPGPKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateRoom mocks base method.
func (m *MockRoomStore) CreateRoom(ctx context.Context, displayName string, creatorID store.UserID, isDM bool) (store.RoomID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, displayName, creatorID, isDM)
	ret0, _ := ret[0].(store.RoomID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockRoomStoreMockRecorder) CreateRoom(ctx, displayName, creatorID, isDM any) *MockRoomStoreCreateRoomCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockRoomStore)(nil).CreateRoom), ctx, displayName, creatorID, isDM)
	return &MockRoomStoreCreateRoomCall{Call: call}
}

// MockRoomStoreCreateRoomCall wrap *gomock.Call
type MockRoomStoreCreateRoomCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreCreateRoomCall) Return(arg0 store.RoomID, arg1 error) *MockRoomStoreCreateRoomCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreCreateRoomCall) Do(f func(context.Context, string, store.UserID, bool) (store.RoomID, error)) *MockRoomStoreCreateRoomCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreCreateRoomCall) DoAndReturn(f func(context.Context, string, store.UserID, bool) (store.RoomID, error)) *MockRoomStoreCreateRoomCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteRoom mocks base method.
func (m *MockRoomStore) DeleteRoom(ctx context.Context, roomID store.RoomID, creatorID store.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoom", ctx, roomID, creatorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoom indicates an expected call of DeleteRoom.
func (mr *MockRoomStoreMockRecorder) DeleteRoom(ctx, roomID, creatorID any) *MockRoomStoreDeleteRoomCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoom", reflect.TypeOf((*MockRoomStore)(nil).DeleteRoom), ctx, roomID, creatorID)
	return &MockRoomStoreDeleteRoomCall{Call: call}
}

// MockRoomStoreDeleteRoomCall wrap *gomock.Call
type MockRoomStoreDeleteRoomCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreDeleteRoomCall) Return(arg0 error) *MockRoomStoreDeleteRoomCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreDeleteRoomCall) Do(f func(context.Context, store.RoomID, store.UserID) error) *MockRoomStoreDeleteRoomCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreDeleteRoomCall) DoAndReturn(f func(context.Context, store.RoomID, store.UserID) error) *MockRoomStoreDeleteRoomCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetOrCreateDMRoom mocks base method.
func (m *MockRoomStore) GetOrCreateDMRoom(ctx context.Context, displayName string, creatorID store.UserID) (store.RoomID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateDMRoom", ctx, displayName, creatorID)
	ret0, _ := ret[0].(store.RoomID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateDMRoom indicates an expected call of GetOrCreateDMRoom.
func (mr *MockRoomStoreMockRecorder) GetOrCreateDMRoom(ctx, displayName, creatorID any) *MockRoomStoreGetOrCreateDMRoomCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateDMRoom", reflect.TypeOf((*MockRoomStore)(nil).GetOrCreateDMRoom), ctx, displayName, creatorID)
	return &MockRoomStoreGetOrCreateDMRoomCall{Call: call}
}

// MockRoomStoreGetOrCreateDMRoomCall wrap *gomock.Call
type MockRoomStoreGetOrCreateDMRoomCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreGetOrCreateDMRoomCall) Return(arg0 store.RoomID, arg1 error) *MockRoomStoreGetOrCreateDMRoomCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreGetOrCreateDMRoomCall) Do(f func(context.Context, string, store.UserID) (store.RoomID, error)) *MockRoomStoreGetOrCreateDMRoomCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreGetOrCreateDMRoomCall) DoAndReturn(f func(context.Context, string, store.UserID) (store.RoomID, error)) *MockRoomStoreGetOrCreateDMRoomCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRoomAccess mocks base method.
func (m *MockRoomStore) GetRoomAccess(ctx context.Context, roomID store.RoomID, userID store.UserID) (bool, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomAccess", ctx, roomID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRoomAccess indicates an expected call of GetRoomAccess.
func (mr *MockRoomStoreMockRecorder) GetRoomAccess(ctx, roomID, userID any) *MockRoomStoreGetRoomAccessCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomAccess", reflect.TypeOf((*MockRoomStore)(nil).GetRoomAccess), ctx, roomID, userID)
	return &MockRoomStoreGetRoomAccessCall{Call: call}
}

// MockRoomStoreGetRoomAccessCall wrap *gomock.Call
type MockRoomStoreGetRoomAccessCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreGetRoomAccessCall) Return(arg0, arg1 bool, arg2 error) *MockRoomStoreGetRoomAccessCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreGetRoomAccessCall) Do(f func(context.Context, store.RoomID, store.UserID) (bool, bool, error)) *MockRoomStoreGetRoomAccessCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreGetRoomAccessCall) DoAndReturn(f func(context.Context, store.RoomID, store.UserID) (bool, bool, error)) *MockRoomStoreGetRoomAccessCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRoomDetail mocks base method.
func (m *MockRoomStore) GetRoomDetail(ctx context.Context, roomID store.RoomID) (store.RoomDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomDetail", ctx, roomID)
	ret0, _ := ret[0].(store.RoomDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomDetail indicates an expected call of GetRoomDetail.
func (mr *MockRoomStoreMockRecorder) GetRoomDetail(ctx, roomID any) *MockRoomStoreGetRoomDetailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomDetail", reflect.TypeOf((*MockRoomStore)(nil).GetRoomDetail), ctx, roomID)
	return &MockRoomStoreGetRoomDetailCall{Call: call}
}

// MockRoomStoreGetRoomDetailCall wrap *gomock.Call
type MockRoomStoreGetRoomDetailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreGetRoomDetailCall) Return(arg0 store.RoomDetail, arg1 error) *MockRoomStoreGetRoomDetailCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreGetRoomDetailCall) Do(f func(context.Context, store.RoomID) (store.RoomDetail, error)) *MockRoomStoreGetRoomDetailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreGetRoomDetailCall) DoAndReturn(f func(context.Context, store.RoomID) (store.RoomDetail, error)) *MockRoomStoreGetRoomDetailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsRoomCreator mocks base method.
func (m *MockRoomStore) IsRoomCreator(ctx context.Context, roomID store.RoomID, userID store.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRoomCreator", ctx, roomID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRoomCreator indicates an expected call of IsRoomCreator.
func (mr *MockRoomStoreMockRecorder) IsRoomCreator(ctx, roomID, userID any) *MockRoomStoreIsRoomCreatorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRoomCreator", reflect.TypeOf((*MockRoomStore)(nil).IsRoomCreator), ctx, roomID, userID)
	return &MockRoomStoreIsRoomCreatorCall{Call: call}
}

// MockRoomStoreIsRoomCreatorCall wrap *gomock.Call
type MockRoomStoreIsRoomCreatorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreIsRoomCreatorCall) Return(arg0 bool, arg1 error) *MockRoomStoreIsRoomCreatorCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreIsRoomCreatorCall) Do(f func(context.Context, store.RoomID, store.UserID) (bool, error)) *MockRoomStoreIsRoomCreatorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreIsRoomCreatorCall) DoAndReturn(f func(context.Context, store.RoomID, store.UserID) (bool, error)) *MockRoomStoreIsRoomCreatorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsRoomMember mocks base method.
func (m *MockRoomStore) IsRoomMember(ctx context.Context, roomID store.RoomID, userID store.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRoomMember", ctx, roomID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRoomMember indicates an expected call of IsRoomMember.
func (mr *MockRoomStoreMockRecorder) IsRoomMember(ctx, roomID, userID any) *MockRoomStoreIsRoomMemberCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRoomMember", reflect.TypeOf((*MockRoomStore)(nil).IsRoomMember), ctx, roomID, userID)
	return &MockRoomStoreIsRoomMemberCall{Call: call}
}

// MockRoomStoreIsRoomMemberCall wrap *gomock.Call
type MockRoomStoreIsRoomMemberCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreIsRoomMemberCall) Return(arg0 bool, arg1 error) *MockRoomStoreIsRoomMemberCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreIsRoomMemberCall) Do(f func(context.Context, store.RoomID, store.UserID) (bool, error)) *MockRoomStoreIsRoomMemberCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreIsRoomMemberCall) DoAndReturn(f func(context.Context, store.RoomID, store.UserID) (bool, error)) *MockRoomStoreIsRoomMemberCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsRoomPGPRequired mocks base method.
func (m *MockRoomStore) IsRoomPGPRequired(ctx context.Context, roomID store.RoomID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRoomPGPRequired", ctx, roomID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRoomPGPRequired indicates an expected call of IsRoomPGPRequired.
func (mr *MockRoomStoreMockRecorder) IsRoomPGPRequired(ctx, roomID any) *MockRoomStoreIsRoomPGPRequiredCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRoomPGPRequired", reflect.TypeOf((*MockRoomStore)(nil).IsRoomPGPRequired), ctx, roomID)
	return &MockRoomStoreIsRoomPGPRequiredCall{Call: call}
}

// MockRoomStoreIsRoomPGPRequiredCall wrap *gomock.Call
type MockRoomStoreIsRoomPGPRequiredCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreIsRoomPGPRequiredCall) Return(arg0 bool, arg1 error) *MockRoomStoreIsRoomPGPRequiredCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreIsRoomPGPRequiredCall) Do(f func(context.Context, store.RoomID) (bool, error)) *MockRoomStoreIsRoomPGPRequiredCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreIsRoomPGPRequiredCall) DoAndReturn(f func(context.Context, store.RoomID) (bool, error)) *MockRoomStoreIsRoomPGPRequiredCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsRoomPublic mocks base method.
func (m *MockRoomStore) IsRoomPublic(ctx context.Context, roomID store.RoomID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRoomPublic", ctx, roomID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRoomPublic indicates an expected call of IsRoomPublic.
func (mr *MockRoomStoreMockRecorder) IsRoomPublic(ctx, roomID any) *MockRoomStoreIsRoomPublicCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRoomPublic", reflect.TypeOf((*MockRoomStore)(nil).IsRoomPublic), ctx, roomID)
	return &MockRoomStoreIsRoomPublicCall{Call: call}
}

// MockRoomStoreIsRoomPublicCall wrap *gomock.Call
type MockRoomStoreIsRoomPublicCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreIsRoomPublicCall) Return(arg0 bool, arg1 error) *MockRoomStoreIsRoomPublicCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreIsRoomPublicCall) Do(f func(context.Context, store.RoomID) (bool, error)) *MockRoomStoreIsRoomPublicCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreIsRoomPublicCall) DoAndReturn(f func(context.Context, store.RoomID) (bool, error)) *MockRoomStoreIsRoomPublicCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// JoinRoom mocks base method.
func (m *MockRoomStore) JoinRoom(ctx context.Context, roomID store.RoomID, userID store.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinRoom", ctx, roomID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// JoinRoom indicates an expected call of JoinRoom.
func (mr *MockRoomStoreMockRecorder) JoinRoom(ctx, roomID, userID any) *MockRoomStoreJoinRoomCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinRoom", reflect.TypeOf((*MockRoomStore)(nil).JoinRoom), ctx, roomID, userID)
	return &MockRoomStoreJoinRoomCall{Call: call}
}

// MockRoomStoreJoinRoomCall wrap *gomock.Call
type MockRoomStoreJoinRoomCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreJoinRoomCall) Return(arg0 error) *MockRoomStoreJoinRoomCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreJoinRoomCall) Do(f func(context.Context, store.RoomID, store.UserID) error) *MockRoomStoreJoinRoomCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreJoinRoomCall) DoAndReturn(f func(context.Context, store.RoomID, store.UserID) error) *MockRoomStoreJoinRoomCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LeaveRoom mocks base method.
func (m *MockRoomStore) LeaveRoom(ctx context.Context, roomID store.RoomID, userID store.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaveRoom", ctx, roomID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LeaveRoom indicates an expected call of LeaveRoom.
func (mr *MockRoomStoreMockRecorder) LeaveRoom(ctx, roomID, userID any) *MockRoomStoreLeaveRoomCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveRoom", reflect.TypeOf((*MockRoomStore)(nil).LeaveRoom), ctx, roomID, userID)
	return &MockRoomStoreLeaveRoomCall{Call: call}
}

// MockRoomStoreLeaveRoomCall wrap *gomock.Call
type MockRoomStoreLeaveRoomCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreLeaveRoomCall) Return(arg0 error) *MockRoomStoreLeaveRoomCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreLeaveRoomCall) Do(f func(context.Context, store.RoomID, store.UserID) error) *MockRoomStoreLeaveRoomCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreLeaveRoomCall) DoAndReturn(f func(context.Context, store.RoomID, store.UserID) error) *MockRoomStoreLeaveRoomCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListAllRooms mocks base method.
func (m *MockRoomStore) ListAllRooms(ctx context.Context) ([]store.RoomDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllRooms", ctx)
	ret0, _ := ret[0].([]store.RoomDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllRooms indicates an expected call of ListAllRooms.
func (mr *MockRoomStoreMockRecorder) ListAllRooms(ctx any) *MockRoomStoreListAllRoomsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllRooms", reflect.TypeOf((*MockRoomStore)(nil).ListAllRooms), ctx)
	return &MockRoomStoreListAllRoomsCall{Call: call}
}

// MockRoomStoreListAllRoomsCall wrap *gomock.Call
type MockRoomStoreListAllRoomsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreListAllRoomsCall) Return(arg0 []store.RoomDetail, arg1 error) *MockRoomStoreListAllRoomsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreListAllRoomsCall) Do(f func(context.Context) ([]store.RoomDetail, error)) *MockRoomStoreListAllRoomsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreListAllRoomsCall) DoAndReturn(f func(context.Context) ([]store.RoomDetail, error)) *MockRoomStoreListAllRoomsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListDMRoomsByMember mocks base method.
func (m *MockRoomStore) ListDMRoomsByMember(ctx context.Context, userID store.UserID) ([]store.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDMRoomsByMember", ctx, userID)
	ret0, _ := ret[0].([]store.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDMRoomsByMember indicates an expected call of ListDMRoomsByMember.
func (mr *MockRoomStoreMockRecorder) ListDMRoomsByMember(ctx, userID any) *MockRoomStoreListDMRoomsByMemberCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDMRoomsByMember", reflect.TypeOf((*MockRoomStore)(nil).ListDMRoomsByMember), ctx, userID)
	return &MockRoomStoreListDMRoomsByMemberCall{Call: call}
}

// MockRoomStoreListDMRoomsByMemberCall wrap *gomock.Call
type MockRoomStoreListDMRoomsByMemberCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreListDMRoomsByMemberCall) Return(arg0 []store.Room, arg1 error) *MockRoomStoreListDMRoomsByMemberCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreListDMRoomsByMemberCall) Do(f func(context.Context, store.UserID) ([]store.Room, error)) *MockRoomStoreListDMRoomsByMemberCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreListDMRoomsByMemberCall) DoAndReturn(f func(context.Context, store.UserID) ([]store.Room, error)) *MockRoomStoreListDMRoomsByMemberCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListPublicRooms mocks base method.
func (m *MockRoomStore) ListPublicRooms(ctx context.Context, userID store.UserID) ([]store.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublicRooms", ctx, userID)
	ret0, _ := ret[0].([]store.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublicRooms indicates an expected call of ListPublicRooms.
func (mr *MockRoomStoreMockRecorder) ListPublicRooms(ctx, userID any) *MockRoomStoreListPublicRoomsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublicRooms", reflect.TypeOf((*MockRoomStore)(nil).ListPublicRooms), ctx, userID)
	return &MockRoomStoreListPublicRoomsCall{Call: call}
}

// MockRoomStoreListPublicRoomsCall wrap *gomock.Call
type MockRoomStoreListPublicRoomsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreListPublicRoomsCall) Return(arg0 []store.Room, arg1 error) *MockRoomStoreListPublicRoomsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreListPublicRoomsCall) Do(f func(context.Context, store.UserID) ([]store.Room, error)) *MockRoomStoreListPublicRoomsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreListPublicRoomsCall) DoAndReturn(f func(context.Context, store.UserID) ([]store.Room, error)) *MockRoomStoreListPublicRoomsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListRoomMembersWithPGP mocks base method.
func (m *MockRoomStore) ListRoomMembersWithPGP(ctx context.Context, roomID store.RoomID) ([]store.RoomMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoomMembersWithPGP", ctx, roomID)
	ret0, _ := ret[0].([]store.RoomMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoomMembersWithPGP indicates an expected call of ListRoomMembersWithPGP.
func (mr *MockRoomStoreMockRecorder) ListRoomMembersWithPGP(ctx, roomID any) *MockRoomStoreListRoomMembersWithPGPCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoomMembersWithPGP", reflect.TypeOf((*MockRoomStore)(nil).ListRoomMembersWithPGP), ctx, roomID)
	return &MockRoomStoreListRoomMembersWithPGPCall{Call: call}
}

// MockRoomStoreListRoomMembersWithPGPCall wrap *gomock.Call
type MockRoomStoreListRoomMembersWithPGPCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreListRoomMembersWithPGPCall) Return(arg0 []store.RoomMember, arg1 error) *MockRoomStoreListRoomMembersWithPGPCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreListRoomMembersWithPGPCall) Do(f func(context.Context, store.RoomID) ([]store.RoomMember, error)) *MockRoomStoreListRoomMembersWithPGPCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreListRoomMembersWithPGPCall) DoAndReturn(f func(context.Context, store.RoomID) ([]store.RoomMember, error)) *MockRoomStoreListRoomMembersWithPGPCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListRoomsByCreator mocks base method.
func (m *MockRoomStore) ListRoomsByCreator(ctx context.Context, userID store.UserID) ([]store.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoomsByCreator", ctx, userID)
	ret0, _ := ret[0].([]store.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoomsByCreator indicates an expected call of ListRoomsByCreator.
func (mr *MockRoomStoreMockRecorder) ListRoomsByCreator(ctx, userID any) *MockRoomStoreListRoomsByCreatorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoomsByCreator", reflect.TypeOf((*MockRoomStore)(nil).ListRoomsByCreator), ctx, userID)
	return &MockRoomStoreListRoomsByCreatorCall{Call: call}
}

// MockRoomStoreListRoomsByCreatorCall wrap *gomock.Call
type MockRoomStoreListRoomsByCreatorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreListRoomsByCreatorCall) Return(arg0 []store.Room, arg1 error) *MockRoomStoreListRoomsByCreatorCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreListRoomsByCreatorCall) Do(f func(context.Context, store.UserID) ([]store.Room, error)) *MockRoomStoreListRoomsByCreatorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreListRoomsByCreatorCall) DoAndReturn(f func(context.Context, store.UserID) ([]store.Room, error)) *MockRoomStoreListRoomsByCreatorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListRoomsByMember mocks base method.
func (m *MockRoomStore) ListRoomsByMember(ctx context.Context, userID store.UserID) ([]store.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoomsByMember", ctx, userID)
	ret0, _ := ret[0].([]store.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoomsByMember indicates an expected call of ListRoomsByMember.
func (mr *MockRoomStoreMockRecorder) ListRoomsByMember(ctx, userID any) *MockRoomStoreListRoomsByMemberCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoomsByMember", reflect.TypeOf((*MockRoomStore)(nil).ListRoomsByMember), ctx, userID)
	return &MockRoomStoreListRoomsByMemberCall{Call: call}
}

// MockRoomStoreListRoomsByMemberCall wrap *gomock.Call
type MockRoomStoreListRoomsByMemberCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreListRoomsByMemberCall) Return(arg0 []store.Room, arg1 error) *MockRoomStoreListRoomsByMemberCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreListRoomsByMemberCall) Do(f func(context.Context, store.UserID) ([]store.Room, error)) *MockRoomStoreListRoomsByMemberCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreListRoomsByMemberCall) DoAndReturn(f func(context.Context, store.UserID) ([]store.Room, error)) *MockRoomStoreListRoomsByMemberCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveMember mocks base method.
func (m *MockRoomStore) RemoveMember(ctx context.Context, roomID store.RoomID, memberID, creatorID store.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, roomID, memberID, creatorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockRoomStoreMockRecorder) RemoveMember(ctx, roomID, memberID, creatorID any) *MockRoomStoreRemoveMemberCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockRoomStore)(nil).RemoveMember), ctx, roomID, memberID, creatorID)
	return &MockRoomStoreRemoveMemberCall{Call: call}
}

// MockRoomStoreRemoveMemberCall wrap *gomock.Call
type MockRoomStoreRemoveMemberCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreRemoveMemberCall) Return(arg0 error) *MockRoomStoreRemoveMemberCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreRemoveMemberCall) Do(f func(context.Context, store.RoomID, store.UserID, store.UserID) error) *MockRoomStoreRemoveMemberCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreRemoveMemberCall) DoAndReturn(f func(context.Context, store.RoomID, store.UserID, store.UserID) error) *MockRoomStoreRemoveMemberCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetRoomMembersCanInvite mocks base method.
func (m *MockRoomStore) SetRoomMembersCanInvite(ctx context.Context, roomID store.RoomID, creatorID store.UserID, value bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRoomMembersCanInvite", ctx, roomID, creatorID, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRoomMembersCanInvite indicates an expected call of SetRoomMembersCanInvite.
func (mr *MockRoomStoreMockRecorder) SetRoomMembersCanInvite(ctx, roomID, creatorID, value any) *MockRoomStoreSetRoomMembersCanInviteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRoomMembersCanInvite", reflect.TypeOf((*MockRoomStore)(nil).SetRoomMembersCanInvite), ctx, roomID, creatorID, value)
	return &MockRoomStoreSetRoomMembersCanInviteCall{Call: call}
}

// MockRoomStoreSetRoomMembersCanInviteCall wrap *gomock.Call
type MockRoomStoreSetRoomMembersCanInviteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreSetRoomMembersCanInviteCall) Return(arg0 error) *MockRoomStoreSetRoomMembersCanInviteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreSetRoomMembersCanInviteCall) Do(f func(context.Context, store.RoomID, store.UserID, bool) error) *MockRoomStoreSetRoomMembersCanInviteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreSetRoomMembersCanInviteCall) DoAndReturn(f func(context.Context, store.RoomID, store.UserID, bool) error) *MockRoomStoreSetRoomMembersCanInviteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetRoomPGPRequired mocks base method.
func (m *MockRoomStore) SetRoomPGPRequired(ctx context.Context, roomID store.RoomID, creatorID store.UserID, value bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRoomPGPRequired", ctx, roomID, creatorID, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRoomPGPRequired indicates an expected call of SetRoomPGPRequired.
func (mr *MockRoomStoreMockRecorder) SetRoomPGPRequired(ctx, roomID, creatorID, value any) *MockRoomStoreSetRoomPGPRequiredCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRoomPGPRequired", reflect.TypeOf((*MockRoomStore)(nil).SetRoomPGPRequired), ctx, roomID, creatorID, value)
	return &MockRoomStoreSetRoomPGPRequiredCall{Call: call}
}

// MockRoomStoreSetRoomPGPRequiredCall wrap *gomock.Call
type MockRoomStoreSetRoomPGPRequiredCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreSetRoomPGPRequiredCall) Return(arg0 error) *MockRoomStoreSetRoomPGPRequiredCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreSetRoomPGPRequiredCall) Do(f func(context.Context, store.RoomID, store.UserID, bool) error) *MockRoomStoreSetRoomPGPRequiredCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreSetRoomPGPRequiredCall) DoAndReturn(f func(context.Context, store.RoomID, store.UserID, bool) error) *MockRoomStoreSetRoomPGPRequiredCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetRoomPublic mocks base method.
func (m *MockRoomStore) SetRoomPublic(ctx context.Context, roomID store.RoomID, creatorID store.UserID, value bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRoomPublic", ctx, roomID, creatorID, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRoomPublic indicates an expected call of SetRoomPublic.
func (mr *MockRoomStoreMockRecorder) SetRoomPublic(ctx, roomID, creatorID, value any) *MockRoomStoreSetRoomPublicCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRoomPublic", reflect.TypeOf((*MockRoomStore)(nil).SetRoomPublic), ctx, roomID, creatorID, value)
	return &MockRoomStoreSetRoomPublicCall{Call: call}
}

// MockRoomStoreSetRoomPublicCall wrap *gomock.Call
type MockRoomStoreSetRoomPublicCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreSetRoomPublicCall) Return(arg0 error) *MockRoomStoreSetRoomPublicCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreSetRoomPublicCall) Do(f func(context.Context, store.RoomID, store.UserID, bool) error) *MockRoomStoreSetRoomPublicCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreSetRoomPublicCall) DoAndReturn(f func(context.Context, store.RoomID, store.UserID, bool) error) *MockRoomStoreSetRoomPublicCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpsertRoomUserPGPKeyWithChallenge mocks base method.
func (m *MockRoomStore) UpsertRoomUserPGPKeyWithChallenge(ctx context.Context, roomID store.RoomID, userID store.UserID, publicKey, fingerprint, challengeCiphertext string, challengeHash []byte, challengeExpiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRoomUserPGPKeyWithChallenge", ctx, roomID, userID, publicKey, fingerprint, challengeCiphertext, challengeHash, challengeExpiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertRoomUserPGPKeyWithChallenge indicates an expected call of UpsertRoomUserPGPKeyWithChallenge.
func (mr *MockRoomStoreMockRecorder) UpsertRoomUserPGPKeyWithChallenge(ctx, roomID, userID, publicKey, fingerprint, challengeCiphertext, challengeHash, challengeExpiresAt any) *MockRoomStoreUpsertRoomUserPGPKeyWithChallengeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRoomUserPGPKeyWithChallenge", reflect.TypeOf((*MockRoomStore)(nil).UpsertRoomUserPGPKeyWithChallenge), ctx, roomID, userID, publicKey, fingerprint, challengeCiphertext, challengeHash, challengeExpiresAt)
	return &MockRoomStoreUpsertRoomUserPGPKeyWithChallengeCall{Call: call}
}

// MockRoomStoreUpsertRoomUserPGPKeyWithChallengeCall wrap *gomock.Call
type MockRoomStoreUpsertRoomUserPGPKeyWithChallengeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreUpsertRoomUserPGPKeyWithChallengeCall) Return(arg0 error) *MockRoomStoreUpsertRoomUserPGPKeyWithChallengeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreUpsertRoomUserPGPKeyWithChallengeCall) Do(f func(context.Context, store.RoomID, store.UserID, string, string, string, []byte, time.Time) error) *MockRoomStoreUpsertRoomUserPGPKeyWithChallengeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreUpsertRoomUserPGPKeyWithChallengeCall) DoAndReturn(f func(context.Context, store.RoomID, store.UserID, string, string, string, []byte, time.Time) error) *MockRoomStoreUpsertRoomUserPGPKeyWithChallengeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// VerifyRoomUserPGPChallenge mocks base method.
func (m *MockRoomStore) VerifyRoomUserPGPChallenge(ctx context.Context, roomID store.RoomID, userID store.UserID, providedPlaintext string, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRoomUserPGPChallenge", ctx, roomID, userID, providedPlaintext, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyRoomUserPGPChallenge indicates an expected call of VerifyRoomUserPGPChallenge.
func (mr *MockRoomStoreMockRecorder) VerifyRoomUserPGPChallenge(ctx, roomID, userID, providedPlaintext, now any) *MockRoomStoreVerifyRoomUserPGPChallengeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRoomUserPGPChallenge", reflect.TypeOf((*MockRoomStore)(nil).VerifyRoomUserPGPChallenge), ctx, roomID, userID, providedPlaintext, now)
	return &MockRoomStoreVerifyRoomUserPGPChallengeCall{Call: call}
}

// MockRoomStoreVerifyRoomUserPGPChallengeCall wrap *gomock.Call
type MockRoomStoreVerifyRoomUserPGPChallengeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoomStoreVerifyRoomUserPGPChallengeCall) Return(arg0 error) *MockRoomStoreVerifyRoomUserPGPChallengeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoomStoreVerifyRoomUserPGPChallengeCall) Do(f func(context.Context, store.RoomID, store.UserID, string, time.Time) error) *MockRoomStoreVerifyRoomUserPGPChallengeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoomStoreVerifyRoomUserPGPChallengeCall) DoAndReturn(f func(context.Context, store.RoomID, store.UserID, string, time.Time) error) *MockRoomStoreVerifyRoomUserPGPChallengeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockInviteStore is a mock of InviteStore interface.
type MockInviteStore struct {
	ctrl     *gomock.Controller
	recorder *MockInviteStoreMockRecorder
	isgomock struct{}
}

// MockInviteStoreMockRecorder is the mock recorder for MockInviteStore.
type MockInviteStoreMockRecorder struct {
	mock *MockInviteStore
}

// NewMockInviteStore creates a new mock instance.
func NewMockInviteStore(ctrl *gomock.Controller) *MockInviteStore {
	mock := &MockInviteStore{ctrl: ctrl}
	mock.recorder = &MockInviteStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInviteStore) EXPECT() *MockInviteStoreMockRecorder {
	return m.recorder
}

// AcceptInvite mocks base method.
func (m *MockInviteStore) AcceptInvite(ctx context.Context, inviteID store.InviteID, userID store.UserID) (store.RoomID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptInvite", ctx, inviteID, userID)
	ret0, _ := ret[0].(store.RoomID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptInvite indicates an expected call of AcceptInvite.
func (mr *MockInviteStoreMockRecorder) AcceptInvite(ctx, inviteID, userID any) *MockInviteStoreAcceptInviteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptInvite", reflect.TypeOf((*MockInviteStore)(nil).AcceptInvite), ctx, inviteID, userID)
	return &MockInviteStoreAcceptInviteCall{Call: call}
}

// MockInviteStoreAcceptInviteCall wrap *gomock.Call
type MockInviteStoreAcceptInviteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInviteStoreAcceptInviteCall) Return(arg0 store.RoomID, arg1 error) *MockInviteStoreAcceptInviteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInviteStoreAcceptInviteCall) Do(f func(context.Context, store.InviteID, store.UserID) (store.RoomID, error)) *MockInviteStoreAcceptInviteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInviteStoreAcceptInviteCall) DoAndReturn(f func(context.Context, store.InviteID, store.UserID) (store.RoomID, error)) *MockInviteStoreAcceptInviteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CancelInvite mocks base method.
func (m *MockInviteStore) CancelInvite(ctx context.Context, inviteID store.InviteID, actingUserID store.UserID) (store.RoomID, store.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelInvite", ctx, inviteID, actingUserID)
	ret0, _ := ret[0].(store.RoomID)
	ret1, _ := ret[1].(store.UserID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CancelInvite indicates an expected call of CancelInvite.
func (mr *MockInviteStoreMockRecorder) CancelInvite(ctx, inviteID, actingUserID any) *MockInviteStoreCancelInviteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelInvite", reflect.TypeOf((*MockInviteStore)(nil).CancelInvite), ctx, inviteID, actingUserID)
	return &MockInviteStoreCancelInviteCall{Call: call}
}

// MockInviteStoreCancelInviteCall wrap *gomock.Call
type MockInviteStoreCancelInviteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInviteStoreCancelInviteCall) Return(arg0 store.RoomID, arg1 store.UserID, arg2 error) *MockInviteStoreCancelInviteCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInviteStoreCancelInviteCall) Do(f func(context.Context, store.InviteID, store.UserID) (store.RoomID, store.UserID, error)) *MockInviteStoreCancelInviteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInviteStoreCancelInviteCall) DoAndReturn(f func(context.Context, store.InviteID, store.UserID) (store.RoomID, store.UserID, error)) *MockInviteStoreCancelInviteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateInvite mocks base method.
func (m *MockInviteStore) CreateInvite(ctx context.Context, roomID store.RoomID, inviterID store.UserID, inviteeUsername string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvite", ctx, roomID, inviterID, inviteeUsername, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInvite indicates an expected call of CreateInvite.
func (mr *MockInviteStoreMockRecorder) CreateInvite(ctx, roomID, inviterID, inviteeUsername, expiresAt any) *MockInviteStoreCreateInviteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvite", reflect.TypeOf((*MockInviteStore)(nil).CreateInvite), ctx, roomID, inviterID, inviteeUsername, expiresAt)
	return &MockInviteStoreCreateInviteCall{Call: call}
}

// MockInviteStoreCreateInviteCall wrap *gomock.Call
type MockInviteStoreCreateInviteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInviteStoreCreateInviteCall) Return(arg0 error) *MockInviteStoreCreateInviteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInviteStoreCreateInviteCall) Do(f func(context.Context, store.RoomID, store.UserID, string, time.Time) error) *MockInviteStoreCreateInviteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInviteStoreCreateInviteCall) DoAndReturn(f func(context.Context, store.RoomID, store.UserID, string, time.Time) error) *MockInviteStoreCreateInviteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeclineInvite mocks base method.
func (m *MockInviteStore) DeclineInvite(ctx context.Context, inviteID store.InviteID, userID store.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeclineInvite", ctx, inviteID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeclineInvite indicates an expected call of DeclineInvite.
func (mr *MockInviteStoreMockRecorder) DeclineInvite(ctx, inviteID, userID any) *MockInviteStoreDeclineInviteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeclineInvite", reflect.TypeOf((*MockInviteStore)(nil).DeclineInvite), ctx, inviteID, userID)
	return &MockInviteStoreDeclineInviteCall{Call: call}
}

// MockInviteStoreDeclineInviteCall wrap *gomock.Call
type MockInviteStoreDeclineInviteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInviteStoreDeclineInviteCall) Return(arg0 error) *MockInviteStoreDeclineInviteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInviteStoreDeclineInviteCall) Do(f func(context.Context, store.InviteID, store.UserID) error) *MockInviteStoreDeclineInviteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInviteStoreDeclineInviteCall) DoAndReturn(f func(context.Context, store.InviteID, store.UserID) error) *MockInviteStoreDeclineInviteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteExpiredInvites mocks base method.
func (m *MockInviteStore) DeleteExpiredInvites(ctx context.Context, now time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredInvites", ctx, now)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredInvites indicates an expected call of DeleteExpiredInvites.
func (mr *MockInviteStoreMockRecorder) DeleteExpiredInvites(ctx, now any) *MockInviteStoreDeleteExpiredInvitesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredInvites", reflect.TypeOf((*MockInviteStore)(nil).DeleteExpiredInvites), ctx, now)
	return &MockInviteStoreDeleteExpiredInvitesCall{Call: call}
}

// MockInviteStoreDeleteExpiredInvitesCall wrap *gomock.Call
type MockInviteStoreDeleteExpiredInvitesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInviteStoreDeleteExpiredInvitesCall) Return(arg0 int64, arg1 error) *MockInviteStoreDeleteExpiredInvitesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInviteStoreDeleteExpiredInvitesCall) Do(f func(context.Context, time.Time) (int64, error)) *MockInviteStoreDeleteExpiredInvitesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInviteStoreDeleteExpiredInvitesCall) DoAndReturn(f func(context.Context, time.Time) (int64, error)) *MockInviteStoreDeleteExpiredInvitesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListInvitesForRoom mocks base method.
func (m *MockInviteStore) ListInvitesForRoom(ctx context.Context, roomID store.RoomID) ([]store.InviteForRoom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvitesForRoom", ctx, roomID)
	ret0, _ := ret[0].([]store.InviteForRoom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvitesForRoom indicates an expected call of ListInvitesForRoom.
func (mr *MockInviteStoreMockRecorder) ListInvitesForRoom(ctx, roomID any) *MockInviteStoreListInvitesForRoomCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvitesForRoom", reflect.TypeOf((*MockInviteStore)(nil).ListInvitesForRoom), ctx, roomID)
	return &MockInviteStoreListInvitesForRoomCall{Call: call}
}

// MockInviteStoreListInvitesForRoomCall wrap *gomock.Call
type MockInviteStoreListInvitesForRoomCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInviteStoreListInvitesForRoomCall) Return(arg0 []store.InviteForRoom, arg1 error) *MockInviteStoreListInvitesForRoomCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInviteStoreListInvitesForRoomCall) Do(f func(context.Context, store.RoomID) ([]store.InviteForRoom, error)) *MockInviteStoreListInvitesForRoomCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInviteStoreListInvitesForRoomCall) DoAndReturn(f func(context.Context, store.RoomID) ([]store.InviteForRoom, error)) *MockInviteStoreListInvitesForRoomCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListInvitesForUser mocks base method.
func (m *MockInviteStore) ListInvitesForUser(ctx context.Context, userID store.UserID) ([]store.InviteForUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvitesForUser", ctx, userID)
	ret0, _ := ret[0].([]store.InviteForUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvitesForUser indicates an expected call of ListInvitesForUser.
func (mr *MockInviteStoreMockRecorder) ListInvitesForUser(ctx, userID any) *MockInviteStoreListInvitesForUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvitesForUser", reflect.TypeOf((*MockInviteStore)(nil).ListInvitesForUser), ctx, userID)
	return &MockInviteStoreListInvitesForUserCall{Call: call}
}

// MockInviteStoreListInvitesForUserCall wrap *gomock.Call
type MockInviteStoreListInvitesForUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInviteStoreListInvitesForUserCall) Return(arg0 []store.InviteForUser, arg1 error) *MockInviteStoreListInvitesForUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInviteStoreListInvitesForUserCall) Do(f func(context.Context, store.UserID) ([]store.InviteForUser, error)) *MockInviteStoreListInvitesForUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInviteStoreListInvitesForUserCall) DoAndReturn(f func(context.Context, store.UserID) ([]store.InviteForUser, error)) *MockInviteStoreListInvitesForUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RoomIDForInvite mocks base method.
func (m *MockInviteStore) RoomIDForInvite(ctx context.Context, inviteID store.InviteID) (store.RoomID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoomIDForInvite", ctx, inviteID)
	ret0, _ := ret[0].(store.RoomID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoomIDForInvite indicates an expected call of RoomIDForInvite.
func (mr *MockInviteStoreMockRecorder) RoomIDForInvite(ctx, inviteID any) *MockInviteStoreRoomIDForInviteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoomIDForInvite", reflect.TypeOf((*MockInviteStore)(nil).RoomIDForInvite), ctx, inviteID)
	return &MockInviteStoreRoomIDForInviteCall{Call: call}
}

// MockInviteStoreRoomIDForInviteCall wrap *gomock.Call
type MockInviteStoreRoomIDForInviteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInviteStoreRoomIDForInviteCall) Return(arg0 store.RoomID, arg1 error) *MockInviteStoreRoomIDForInviteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInviteStoreRoomIDForInviteCall) Do(f func(context.Context, store.InviteID) (store.RoomID, error)) *MockInviteStoreRoomIDForInviteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInviteStoreRoomIDForInviteCall) DoAndReturn(f func(context.Context, store.InviteID) (store.RoomID, error)) *MockInviteStoreRoomIDForInviteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockMessageStore is a mock of MessageStore interface.
type MockMessageStore struct {
	ctrl     *gomock.Controller
	recorder *MockMessageStoreMockRecorder
	isgomock struct{}
}

// MockMessageStoreMockRecorder is the mock recorder for MockMessageStore.
type MockMessageStoreMockRecorder struct {
	mock *MockMessageStore
}

// NewMockMessageStore creates a new mock instance.
func NewMockMessageStore(ctrl *gomock.Controller) *MockMessageStore {
	mock := &MockMessageStore{ctrl: ctrl}
	mock.recorder = &MockMessageStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageStore) EXPECT() *MockMessageStoreMockRecorder {
	return m.recorder
}

// CreateMessage mocks base method.
func (m *MockMessageStore) CreateMessage(ctx context.Context, roomID store.RoomID, userID store.UserID, username, message string, whisper bool, targetUserID *store.UserID, preEncrypted bool) (store.MessageID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", ctx, roomID, userID, username, message, whisper, targetUserID, preEncrypted)
	ret0, _ := ret[0].(store.MessageID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockMessageStoreMockRecorder) CreateMessage(ctx, roomID, userID, username, message, whisper, targetUserID, preEncrypted any) *MockMessageStoreCreateMessageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockMessageStore)(nil).CreateMessage), ctx, roomID, userID, username, message, whisper, targetUserID, preEncrypted)
	return &MockMessageStoreCreateMessageCall{Call: call}
}

// MockMessageStoreCreateMessageCall wrap *gomock.Call
type MockMessageStoreCreateMessageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMessageStoreCreateMessageCall) Return(arg0 store.MessageID, arg1 error) *MockMessageStoreCreateMessageCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMessageStoreCreateMessageCall) Do(f func(context.Context, store.RoomID, store.UserID, string, string, bool, *store.UserID, bool) (store.MessageID, error)) *MockMessageStoreCreateMessageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMessageStoreCreateMessageCall) DoAndReturn(f func(context.Context, store.RoomID, store.UserID, string, string, bool, *store.UserID, bool) (store.MessageID, error)) *MockMessageStoreCreateMessageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListMessages mocks base method.
func (m *MockMessageStore) ListMessages(ctx context.Context, roomID store.RoomID, userID store.UserID, beforeID store.MessageID, limit int) ([]store.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, roomID, userID, beforeID, limit)
	ret0, _ := ret[0].([]store.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockMessageStoreMockRecorder) ListMessages(ctx, roomID, userID, beforeID, limit any) *MockMessageStoreListMessagesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockMessageStore)(nil).ListMessages), ctx, roomID, userID, beforeID, limit)
	return &MockMessageStoreListMessagesCall{Call: call}
}

// MockMessageStoreListMessagesCall wrap *gomock.Call
type MockMessageStoreListMessagesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMessageStoreListMessagesCall) Return(arg0 []store.Message, arg1 error) *MockMessageStoreListMessagesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMessageStoreListMessagesCall) Do(f func(context.Context, store.RoomID, store.UserID, store.MessageID, int) ([]store.Message, error)) *MockMessageStoreListMessagesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMessageStoreListMessagesCall) DoAndReturn(f func(context.Context, store.RoomID, store.UserID, store.MessageID, int) ([]store.Message, error)) *MockMessageStoreListMessagesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListMessagesAfterID mocks base method.
func (m *MockMessageStore) ListMessagesAfterID(ctx context.Context, roomID store.RoomID, userID store.UserID, afterID store.MessageID, limit int) ([]store.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessagesAfterID", ctx, roomID, userID, afterID, limit)
	ret0, _ := ret[0].([]store.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessagesAfterID indicates an expected call of ListMessagesAfterID.
func (mr *MockMessageStoreMockRecorder) ListMessagesAfterID(ctx, roomID, userID, afterID, limit any) *MockMessageStoreListMessagesAfterIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessagesAfterID", reflect.TypeOf((*MockMessageStore)(nil).ListMessagesAfterID), ctx, roomID, userID, afterID, limit)
	return &MockMessageStoreListMessagesAfterIDCall{Call: call}
}

// MockMessageStoreListMessagesAfterIDCall wrap *gomock.Call
type MockMessageStoreListMessagesAfterIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMessageStoreListMessagesAfterIDCall) Return(arg0 []store.Message, arg1 error) *MockMessageStoreListMessagesAfterIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMessageStoreListMessagesAfterIDCall) Do(f func(context.Context, store.RoomID, store.UserID, store.MessageID, int) ([]store.Message, error)) *MockMessageStoreListMessagesAfterIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMessageStoreListMessagesAfterIDCall) DoAndReturn(f func(context.Context, store.RoomID, store.UserID, store.MessageID, int) ([]store.Message, error)) *MockMessageStoreListMessagesAfterIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SearchMessages mocks base method.
func (m *MockMessageStore) SearchMessages(ctx context.Context, roomID store.RoomID, userID store.UserID, query string, limit int) ([]store.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMessages", ctx, roomID, userID, query, limit)
	ret0, _ := ret[0].([]store.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMessages indicates an expected call of SearchMessages.
func (mr *MockMessageStoreMockRecorder) SearchMessages(ctx, roomID, userID, query, limit any) *MockMessageStoreSearchMessagesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMessages", reflect.TypeOf((*MockMessageStore)(nil).SearchMessages), ctx, roomID, userID, query, limit)
	return &MockMessageStoreSearchMessagesCall{Call: call}
}

// MockMessageStoreSearchMessagesCall wrap *gomock.Call
type MockMessageStoreSearchMessagesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMessageStoreSearchMessagesCall) Return(arg0 []store.Message, arg1 error) *MockMessageStoreSearchMessagesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMessageStoreSearchMessagesCall) Do(f func(context.Context, store.RoomID, store.UserID, string, int) ([]store.Message, error)) *MockMessageStoreSearchMessagesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMessageStoreSearchMessagesCall) DoAndReturn(f func(context.Context, store.RoomID, store.UserID, string, int) ([]store.Message, error)) *MockMessageStoreSearchMessagesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
