name: Image

on:
  push:
    branches: [main]
    paths-ignore: ["**.md"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image:
    uses: jchevertonwynne/workflows/.github/workflows/build-image.yml@main
    permissions:
      contents: read
      packages: write
